### ISSUE TITLE
A question for the details

### ISSUE THREAD

**Issue by liuyuchen6666** [matsui528/deep1b_gt#1]
Hello, thanks for your excellent job, do you directly pick the top 1 million database vectors as Deep 1M dataset? (Maybe I only need to download base00 to construct the deep 1M dataset you use?).
thanks a lot, I am looking forward to your reply.
Best regards!

**Comment by matsui528** [comment]
Yes, you should change this line to specify base00 (I haven't tested it though)
https://github.com/matsui528/deep1b_gt/blob/master/compute_gt.py#L52

**Comment by matsui528** [comment]
It doesn't seem to work...  I found that mmap fails.
```
Traceback (most recent call last):
  File "compute_gt.py", line 64, in <module>
    fire.Fire(run)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "compute_gt.py", line 52, in run
    xb = fvecs_mmap(str(root / "base/base_00"))
  File "compute_gt.py", line 25, in fvecs_mmap
    return ivecs_mmap(fname).view('float32')
  File "compute_gt.py", line 19, in ivecs_mmap
    a = np.memmap(fname, dtype='int32', mode='r')
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/memmap.py", line 236, in __new__
    raise ValueError("Size of available data is not a "
ValueError: Size of available data is not a multiple of the data-type size.
```

It's because each base_XX is not 8-byte aligned:
```
-rw-r--r-- 1 root root 10630044057 Jan 15 15:33 base_00
-rw-r--r-- 1 root root 10630044057 Jan 15 16:02 base_01
```
As you can see, base_XX has 10630044057 bytes, which cannot be divided by 8.

One way to solve this is to read base_00 by other methods such as texmex_python https://github.com/Hi-king/read_texmex_dataset_python  This library iteratively reads vectors one by one, thus you can pick up the first 1M vectors even though base_00 is not 8 byte aligned (not tested though, again)

**Comment by matsui528** [comment]
Added a script to download deep1m  https://github.com/matsui528/deep1b_gt#bonus-deep1m
